export const mockDocuments = [
  {
    id: 'react-hooks',
    type: 'PDF',
    subject: 'Computer Science',
    title: 'Introduction to React Hooks',
    description: 'Comprehensive guide to useState, useEffect, and custom hooks',
    category: 'Programming',
    author: 'Dr. Sarah Johnson',
    date: '4/1/2026',
    downloads: 45,
    commentsCount: 12,
    comments: [
      {
        id: 1,
        author: 'James Lee',
        role: 'student',
        date: '4/2/2026',
        content: 'This was a really clear introduction. The useEffect section helped a lot.',
      },
      {
        id: 2,
        author: 'Rachel Moore',
        role: 'student',
        date: '4/3/2026',
        content: 'Could you also add examples for custom hooks with API calls?',
      },
      {
        id: 3,
        author: 'Dr. Sarah Johnson',
        role: 'teacher',
        date: '4/3/2026',
        content: 'Yes, I will upload an advanced follow-up note for asynchronous hooks soon.',
      },
    ],
  },
  {
    id: 'calculus-fundamentals',
    type: 'PDF',
    subject: 'Mathematics',
    title: 'Calculus Fundamentals',
    description: 'Limits, derivatives, and integrals explained with examples',
    category: 'Calculus',
    author: 'Prof. Michael Chen',
    date: '3/28/2026',
    downloads: 78,
    commentsCount: 3,
    comments: [
      {
        id: 1,
        author: 'Alex Kim',
        role: 'student',
        date: '4/6/2026',
        content: 'This material really helped me understand the concept! Thank you for sharing.',
      },
      {
        id: 2,
        author: 'Maria Garcia',
        role: 'student',
        date: '4/7/2026',
        content: 'Could you provide more examples on the advanced topics?',
      },
      {
        id: 3,
        author: 'Prof. Michael Chen',
        role: 'teacher',
        date: '4/7/2026',
        content: "Great question! I'll add a supplementary document with more examples soon.",
      },
    ],
  },
  {
    id: 'world-war-ii-documentary',
    type: 'VIDEO',
    subject: 'History',
    title: 'World War II Documentary',
    description: 'Historical overview of major events from 1939-1945',
    category: 'Modern History',
    author: 'Dr. Emily Brown',
    date: '4/5/2026',
    downloads: 34,
    commentsCount: 8,
    comments: [
      {
        id: 1,
        author: 'Sophia White',
        role: 'student',
        date: '4/6/2026',
        content: 'The timeline explanation was easy to follow and very informative.',
      },
      {
        id: 2,
        author: 'Daniel Scott',
        role: 'student',
        date: '4/7/2026',
        content: 'Can you recommend another video focused more on the Pacific theater?',
      },
      {
        id: 3,
        author: 'Dr. Emily Brown',
        role: 'teacher',
        date: '4/7/2026',
        content: 'Absolutely. I will add another recommended resource in the history section.',
      },
    ],
  },
]

export const getDocumentById = (documentId) =>
  mockDocuments.find((document) => document.id === documentId)
